### ISSUE TITLE
App with id maps has invalid signature

### ISSUE THREAD

**Issue by whisperdancer** [nextcloud/maps#237]
Nextcloud 17.02, Rasperian Buster, Nginx, Php 7

I try to install maps and get this error? Why is this happening and how can I resolve it? Thanks

App with id maps has invalid signature

**Comment by adietz00** [comment]
Confirming error on Nextcloud 17.02, Ubuntu 18.04.3, php7.3 and nginx.

Log shows:

> 

  | Exception: App with id maps has invalid signature/var/www/nextcloud/lib/private/Installer.php - line 186: OC\Installer->downloadApp("*** sensiti ... *")/var/www/nextcloud/settings/Controller/AppSettingsController.php - line 532: OC\Installer->updateAppstoreApp("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170: OC\Settings\Controller\AppSettingsController->updateApp("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "updateApp")/var/www/nextcloud/lib/private/AppFramework/App.php - line 126: OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "updateApp")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OC\\Setting ... r", "updateApp", OC\AppFramew ... {}, { appId: "** ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ appId: "** ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { appId: "** ... "})/var/www/nextcloud/lib/base.php - line 997: OC\Route\Router->match("/settings/apps/update/maps")/var/www/nextcloud/index.php - line 42: OC::handleRequest()
-- | --

**Comment by tacruc** [comment]
Known Issue working on a new release.

**Comment by tacruc** [comment]
Should be fixed with 0.1.4

**Comment by adietz00** [comment]
Still not installing for me... I get the following:

`Exception: Could not extract app maps

    /var/www/nextcloud/lib/private/Installer.php - line 186:

    OC\Installer->downloadApp("*** sensiti ... *")

    /var/www/nextcloud/settings/Controller/AppSettingsController.php - line 532:

    OC\Installer->updateAppstoreApp("*** sensiti ... *")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OC\Settings\Controller\AppSettingsController->updateApp("*** sensiti ... *")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "updateApp")

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 126:

    OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "updateApp")

    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OC\\Setting ... r", "updateApp", OC\AppFramew ... {}, { appId: "** ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ appId: "** ... "})

    /var/www/nextcloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { appId: "** ... "})

    /var/www/nextcloud/lib/base.php - line 997:

    OC\Route\Router->match("/settings/apps/update/maps")

    /var/www/nextcloud/index.php - line 42:

    OC::handleRequest()`

**Comment by JoshuaPettus** [comment]
I'm afraid same for me,  Nextcloud 17.0.2, PHP 7.3.13, Ubuntu 18.04

**Comment by grondinm** [comment]
Still getting this when trying to install. NC:18 PHP:7.4.1

**Comment by tacruc** [comment]
I tried to fix #240  and changed the Tarball, but updating the signiture in the apps store failed. So just exchanging the error message, but not making it worse or beder. Addressed in #254
