### ISSUE TITLE
0.1.4: Could not extract app maps

### ISSUE THREAD

**Issue by vanitasvitae** [nextcloud/maps#240]
Hi!
Updating maps fro 0.1.2 to 0.1.4 fails for me:
```
[core] Error: Exception: Could not extract app maps at <<closure>>

0. /var/www/nextcloud/lib/private/Installer.php line 186
   OC\Installer->downloadApp("*** sensitive parameter replaced ***")
1. /var/www/nextcloud/settings/Controller/AppSettingsController.php line 532
   OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
   OC\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\Cont ... {}, "updateApp")
4. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\Cont ... {}, "updateApp")
5. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OC\\Settings\\C ... r", "updateApp", OC\AppFramework\ ... {}, {appId: "*** sen ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({appId: "*** sen ... "})
7. /var/www/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {appId: "*** sen ... "})
8. /var/www/nextcloud/lib/base.php line 997
   OC\Route\Router->match("/settings/apps/update/maps")
9. /var/www/nextcloud/index.php line 42
   OC::handleRequest()

GET /settings/apps/update/maps
```

I'm running NC 17.0.2 on Debian Buster.

**Comment by tacruc** [comment]
@rullzer do you have an idea. Tar is extracting the archive without error.

**Comment by gringo1er** [comment]
Same issue. By nextcloud integrated update interface, or by downloading tar on apps.nextcloud.com : "corrupted archive"
Thanks!

**Comment by small1** [comment]
Cant install or update to latest maps on any of my instances.

**Comment by JoshuaPettus** [comment]
Same for me  NC 17.0.2,  PHP 7.3.13,  Ubuntu 18.04

**Comment by xila76** [comment]
Same for me NC 17.0.2, PHP 7.3, Debian Buster
But update can be done manually in SSH after downloading tar archive from github releases page and extracting it

**Comment by poVoq** [comment]
Happens for me also for the 18.0.0RC2-apache docker image.

**Comment by tacruc** [comment]
We're investigating. Manually unpacking is working.

**Comment by vanitasvitae** [comment]
Manually installing worked for me too. Nice update! :D

**Comment by Rychu-Pawel** [comment]
I'll only add that update through occ fails too.

**Comment by palto42** [comment]
In the NC logs I see a message about signature issue: "Exception: App with id maps has invalid signature"

**Comment by vanitasvitae** [comment]
> In the NC logs I see a message about signature issue: "Exception: App with id maps has invalid signature"

That sounds more like #237. Are you sure you are trying to update to 0.1.4, not 0.1.3?

**Comment by doc75** [comment]
Same issue with Nextcloud 16.0.7 while trying to upgrade from v0.1.2 to v0.1.4.
Thanks for this great app.

**Comment by palto42** [comment]
> > In the NC logs I see a message about signature issue: "Exception: App with id maps has invalid signature"
> 
> That sounds more like #237. Are you sure you are trying to update to 0.1.4, not 0.1.3?

Thanks @vanitasvitae , you are right. It was an older log entry from this morning.

**Comment by oakbrad** [comment]
> Happens for me also for the 18.0.0RC2-apache docker image.

Same for me after updating to 18.0.0-apache Docker image

**Comment by Exoyds** [comment]
Same on NC 17.0.2, PHP 7.2.24, Ubuntu 18.04.3

**Comment by jancborchardt** [comment]
cc @rullzer @tacruc @eneiluj cause I can’t mediate on this technical issue. What can we do here and/or how can we communicate?

Do we load the extra Mapbox library only after initial install, or how do we keep the package smaller?

**Comment by lyn1337** [comment]
Update failed for me on NC16, same error.
Removing and re-installing failed.
`# sudo -u www-data php -f occ app:install maps
Error: Could not extract app maps`

**Comment by makemegit** [comment]
Guys when i download as zip, there is a comment inside:
4cb2861660711a06ded5a481331022b25e6c9b2a
What is this? md5 sha1, 256 ?

I am asking because:

> 
> $ sha1sum maps-master.zip 
> 51c33b80746d539666fff72d436fac553f70aa2f  maps-master.zip

**Comment by lyn1337** [comment]
@makemegit the id of the latest commit

**Comment by UDZGuru** [comment]
I am also affected by the "could not extract" issue. 

NC17.02, PHP7.3.11, MariaDB 10.3.20

This is the first time an app fails to update. All other apps worked just fine.

**Comment by szucher** [comment]
Hi,
i have the same error. I tried to uninstall the app and try to install again, but this also failed!
Please fix it fast! When the App works, its a very good App!

**Comment by mikweb2017** [comment]
i have the same error. NC 18 PHP 7.3.13

**Comment by Bschalck** [comment]
same error here : 
Nextcloud 17.0.2 , php 7.13.3 

{"reqId":"QQh30CPtOFv5WLRvZa5C","level":3,"time":"2020-01-19T10:54:20+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"Exception","Message":"Could not extract app maps","Code":0,"Trace":[{"file":"\/home\/nextcloud\/lib\/private\/Installer.php","line":186,"function":"downloadApp","class":"OC\\Installer","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"\/home\/nextcloud\/core\/Command\/App\/Update.php","line":105,"function":"updateAppstoreApp","class":"OC\\Installer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/nextcloud\/3rdparty\/symfony\/console\/Command\/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\App\\Update","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/home\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":908,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/home\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":269,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OC\\Core\\Command\\App\\Update"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/home\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":145,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/home\/nextcloud\/lib\/private\/Console\/Application.php","line":213,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/home\/nextcloud\/console.php","line":97,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"\/home\/nextcloud\/occ","line":11,"args":["\/home\/nextcloud\/console.php"],"function":"require_once"}],"File":"\/home\/nextcloud\/lib\/private\/Installer.php","Line":283,"CustomMessage":"--"},"userAgent":"--","version":"17.0.2.1"}

**Comment by rullzer** [comment]
I'm not at my laptop. But it seems there are two issues here.

1. Timeout, this is not something we can really fix. But downloading the file manually should fix it.
2. It seems some systems find the package as not properly signed. I can look into that tomorrow if that is really true or not and if so what to do.

**Comment by NorryNew** [comment]
Due to the Document Server (it is a realy big "app"), I have changed my download timeout, so this should fixed for me, but anyway:
Exception: Could not extract app maps

**Comment by mseed** [comment]
Same problem on my NextCloud 17.0.2 servers.

```
[core] Error: Exception: Could not extract app maps at <<closure>>

0. /var/www/nextcloud/lib/private/Installer.php line 186
   OC\Installer->downloadApp("*** sensitive parameter replaced ***")
1. /var/www/nextcloud/settings/Controller/AppSettingsController.php line 532
   OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
   OC\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\Cont ... {}, "updateApp")
4. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\Cont ... {}, "updateApp")
5. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OC\\Settings\\C ... r", "updateApp", OC\AppFramework\ ... {}, {appId: "*** sen ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({appId: "*** sen ... "})
7. /var/www/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {appId: "*** sen ... "})
8. /var/www/nextcloud/lib/base.php line 997
   OC\Route\Router->match("/settings/apps/update/maps")
9. /var/www/nextcloud/index.php line 42
   OC::handleRequest()

GET /settings/apps/update/maps

```

**Comment by alex-noname** [comment]
> Manually installing worked for me too. Nice update! :D

cd apps
curl https://codeload.github.com/nextcloud/maps/zip/master --output maps.zip
unzip maps.zip
cd ..
sudo -u www-data php -f occ app:install maps
-> maps already installed
sudo -u www-data php -f occ app:enable maps
->PHP Fatal error:  require_once(): Failed opening required '/var/www/nextcloud/apps/maps/lib/Service/../../vendor/autoload.php' (include_path='/var/www/nextcloud/apps/news/vendor/pear/net_url2:/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps') in /var/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php on line 32

line 32 in PhotofilesService.php is:
require_once __DIR__ . '/../../vendor/autoload.php';

Which way is the recommended for command line installation?

**Comment by scottpk** [comment]
Just noting I am having this same issue using the Nextcloud Docker container and UnRAID 6.8.0

**Comment by dugite-code** [comment]
@alex-noname you need to download from the release page not the git repo https://github.com/nextcloud/maps/releases/tag/v0.1.4

```bash
sudo -u www-data php occ app:disable maps
cd apps
mv ./maps ./maps-old
wget https://github.com/nextcloud/maps/releases/download/v0.1.4/maps-0.1.4.tar.gz
tar -xzvf maps-0.1.4.tar.gz
chown -R www-data:www-data ./maps
cd ..
sudo -u www-data php occ app:enable maps
```

**Comment by alex-noname** [comment]
@dugite-code 
Thanks a lot. It works for me too.

**Comment by rullzer** [comment]
That is because manual install doesn't verify the signature that is in the appstore.

Seems indeed that the signature doesn't match.
Could you resign the tarball and try to release it again?

**Comment by alex-noname** [comment]
> Could you resign the tarball and try to release it again?

I agree. It would be the safest, best, and most trustworthy option.

**Comment by probastaller** [comment]
Same case here.
NC 17.0.2 nginx.

- Installed manually and it is working fine :)

**Comment by makemegit** [comment]
@dugite-code 10x . It works.

**Comment by SomeStrangeName** [comment]
Now I see 0.1.3 as version in nextcloud admint page. But seems to have the same error.

**Comment by Art4** [comment]
@SomeStrangeName 0.1.3 has a bug #237, that should be fixed in 0.1.4, but results in this bug. 🙈

**Comment by tacruc** [comment]
> That is because manual install doesn't verify the signature that is in the appstore.
> 
> Seems indeed that the signature doesn't match.
> Could you resign the tarball and try to release it again?

I build a new tarball and updated it on the appstore but the error is still there. If I manually download the archive and compare the Signatures match. Do you have more insight which signature might be wrong

**Comment by tacruc** [comment]
There is something wired with the old and the new archive.

```php
<?php
require_once 'Archive/Tar.php';

$tar =  new Archive_Tar("maps-.tar.gz","gz");
if(!$tar->extract("./")){
    echo("Error\n");
}
```
Unpacks the Archive, but the script outputs Error too.

**Comment by lupinehorror** [comment]
i'm getting this too. nextcloud 17.0.2 trying to upgrade to maps 0.1.4

[core] Error: Exception: Could not extract app maps at <<closure>>

0. */web/lib/private/Installer.php line 186
   OC\Installer->downloadApp("*** sensitive parameter replaced ***")
1. */web/settings/Controller/AppSettingsController.php line 532
   OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
2. */web/lib/private/AppFramework/Http/Dispatcher.php line 170
   OC\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
3. */web/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\Cont ... {}, "updateApp")
4. */web/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\Cont ... {}, "updateApp")
5. */web/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OC\\Settings\\C ... r", "updateApp", OC\AppFramework\ ... {}, {appId: "*** sen ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({appId: "*** sen ... "})
7. */web/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {appId: "*** sen ... "})
8. */web/lib/base.php line 997
   OC\Route\Router->match("/settings/apps/update/maps")
9. */web/index.php line 42
   OC::handleRequest()

GET /index.php/settings/apps/update/maps

**Comment by tacruc** [comment]
Ok, if i take the archive from the make file created with tar -czf the test script two post above fails, but if I compress the folder created by the makefile using ark, the testscript passes. So I will try to upload a manually compressed archive and see if it helps.

**Comment by Bschalck** [comment]
For information, same erreor whan download app on clean NExctloud 18 server : 
Une erreur est survenue durant la requête. Impossible de traiter la demande.
**App with id maps has invalid signature**

**Comment by tacruc** [comment]
> Ok, if i take the archive created by the makefile (with tar -czf) the test script two post above fails, but if I compress the folder created by the makefile using ark, the testscript passes. So I will try to upload a manually compressed archive and see if it helps.

The new build worked for me. Please notice that there are still some open issues:
Most curtial ones:
#239 
#261 
#260 
#247

**Comment by tjeerd13** [comment]
My solution for:

Maps installing with the App installer did not work. (removed en try to reinstall different times.)

I'm not using the default www-data user. I noticed the wrong permsions in the /app/maps map. And there whas a maps-master.zip file in the /app map. With root as owner. After removing that file and removing the /app/maps map.  I could use the web installer again and its al working fine now,

**Comment by scottpk** [comment]
For what it's worth, I was able to uninstall and reinstall successfully
through the UI after the repackaged release (on UnRAID using the Nextcloud
docker container)
