### ISSUE TITLE
Unsupported operand types: int * string in /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php:447

### ISSUE THREAD

**Issue by GHJester** [nextcloud/maps#652]
Hi all,

Nextcloud is running in a docker container on my host. Recently I updated to version 22.1.1. Maps is running with version 0.1.9. Today I checked for another update and have seen that the last cron job execution was 6 days ago, even though I configured to run every 5 minutes.
When I execute the cron job manually by executing `docker exec -u www-data nextcloud php cron.php`, I get the following error output:

```
TypeError: Unsupported operand types: int * string in /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php:447
Stack trace:
#0 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelCanonMakerNotes.php(215): lsolesen\pel\PelIfd->loadSingleValue(Object(lsolesen\pel\PelDataWindow), 4776, 0, 256)
#1 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php(406): lsolesen\pel\PelCanonMakerNotes->load()
#2 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelTiff.php(159): lsolesen\pel\PelIfd->load(Object(lsolesen\pel\PelDataWindow), 10)
#3 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelExif.php(108): lsolesen\pel\PelTiff->load(Object(lsolesen\pel\PelDataWindow))
#4 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(216): lsolesen\pel\PelExif->load(Object(lsolesen\pel\PelDataWindow))
#5 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(126): lsolesen\pel\PelJpeg->load(Object(lsolesen\pel\PelDataWindow))
#6 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(442): lsolesen\pel\PelJpeg->__construct(Object(lsolesen\pel\PelDataWindow))
#7 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(384): OCA\Maps\Service\PhotofilesService->getExifPelBackup(Object(OC\Files\Node\File))
#8 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(264): OCA\Maps\Service\PhotofilesService->getExif(Object(OC\Files\Node\File))
#9 /var/www/html/custom_apps/maps/lib/BackgroundJob/AddPhotoJob.php(56): OCA\Maps\Service\PhotofilesService->addPhotoNow(Object(OC\Files\Node\File), 'XXXXX')
#10 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\Maps\BackgroundJob\AddPhotoJob->run(Array)
#11 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#12 /var/www/html/cron.php(127): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#13 {main}
```

1. This seems for me to be related to https://github.com/pel/pel/issues/156. But this issue is already fixed.
2. As far as I understood Nexcloud 22.1.1 has been upgraded to use PHP 8. This explains the different message `Unsupported operand types: int * string`
3. I think I need to mention that I uploaded a bulk of very old photos to my Nextcloud instance a few days ago. It is very likely that one of them caused that issue. But I don't have any clue how to figure out. But as 1. has been fixed in 2020 I assume that Maps is still using an old version of pel!?

Do you have an idea how to fix or is there something I can change?

Cheers
Jester

**Comment by klaHoadl** [comment]
I changed line 447 and casted the return value from getSize() to int

`$s = (int) PelFormat::getSize($format) * $components;`

**Comment by GHJester** [comment]
@klaHoadl  thx for your help. In the meantime I upgraded to 22.2.0 and the error is gone (for what reason ever). But is seems like that now everything is messed up. In the past I have seen the photo locations on the map, but now I don't see a single photo and its location on the world map anymore.

**Comment by GHJester** [comment]
Something is still weird. There are only around 900 photos displayed, though I have more than 10.000. This definitely needs a fix...

**Comment by elearningdienst** [comment]
Same problem here with PHP 8.0.12 and Nextcloud 22.2.2 (map version 0.1.9).

**Comment by arthurlt** [comment]
I'm having a similar issue running Nextcloud's Docker build.

**Comment by citramon** [comment]
I have a similar issue.

Docker build.
PHP 8.0.12
Nextcloud 22.2.0
Maps 0.1.9.

I think the problem in other package with same types of files. 
I fix it in this [file](https://github.com/pel/pel/blob/master/src/PelCanonMakerNotes.php#L214):
```php
                case PelTag::CANON_CUSTOM_FUNCTIONS:
                    //TODO
                case (256 || 512 || 768):
                    break;
                    //SKIP BECAUSE EXCEPTION
                default:
``` 

The idea is skip files which rise exception 🤷‍♂️

**Comment by kamilkobak** [comment]
I have the same problem

**Comment by DeniGam** [comment]
Thesame error blocks cron job ececution:

`TypeError: Unsupported operand types: int * string in /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php:447
Stack trace:
#0 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelCanonMakerNotes.php(215): lsolesen\pel\PelIfd->loadSingleValue(Object(lsolesen\pel\PelDataWindow), 4906, 0, 256)
#1 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php(406): lsolesen\pel\PelCanonMakerNotes->load()
#2 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelTiff.php(159): lsolesen\pel\PelIfd->load(Object(lsolesen\pel\PelDataWindow), 10)
#3 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelExif.php(108): lsolesen\pel\PelTiff->load(Object(lsolesen\pel\PelDataWindow))
#4 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(216): lsolesen\pel\PelExif->load(Object(lsolesen\pel\PelDataWindow))
#5 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(126): lsolesen\pel\PelJpeg->load(Object(lsolesen\pel\PelDataWindow))
#6 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(442): lsolesen\pel\PelJpeg->__construct(Object(lsolesen\pel\PelDataWindow))
#7 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(384): OCA\Maps\Service\PhotofilesService->getExifPelBackup(Object(OC\Files\Node\File))
#8 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(264): OCA\Maps\Service\PhotofilesService->getExif(Object(OC\Files\Node\File))
#9 /var/www/html/custom_apps/maps/lib/BackgroundJob/AddPhotoJob.php(56): OCA\Maps\Service\PhotofilesService->addPhotoNow(Object(OC\Files\Node\File), 'kroshe4ka.m')
#10 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\Maps\BackgroundJob\AddPhotoJob->run(Array)
#11 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#12 /var/www/html/cron.php(128): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#13 {main}`
NC version 23.0.0.10

**Comment by heminei** [comment]
I have the same error:

```
{
   "reqId":"",
   "level":3,
   "time":"2022-01-04T16:10:02+00:00",
   "remoteAddr":"",
   "user":"--",
   "app":"cron",
   "method":"",
   "url":"--",
   "message":"Unsupported operand types: int * string",
   "userAgent":"--",
   "version":"23.0.0.10",
   "exception":{
      "Exception":"TypeError",
      "Message":"Unsupported operand types: int * string",
      "Code":0,
      "Trace":[
         {
            "file":"/apps/maps/vendor/lsolesen/pel/src/PelIfd.php",
            "line":368,
            "function":"loadSingleValue",
            "class":"lsolesen\\pel\\PelIfd",
            "type":"->"
         },
         {
            "file":"/apps/maps/vendor/lsolesen/pel/src/PelIfd.php",
            "line":350,
            "function":"load",
            "class":"lsolesen\\pel\\PelIfd",
            "type":"->"
         },
         {
            "file":"/apps/maps/vendor/lsolesen/pel/src/PelTiff.php",
            "line":159,
            "function":"load",
            "class":"lsolesen\\pel\\PelIfd",
            "type":"->"
         },
         {
            "file":"/apps/maps/vendor/lsolesen/pel/src/PelExif.php",
            "line":108,
            "function":"load",
            "class":"lsolesen\\pel\\PelTiff",
            "type":"->"
         },
         {
            "file":"/apps/maps/vendor/lsolesen/pel/src/PelJpeg.php",
            "line":216,
            "function":"load",
            "class":"lsolesen\\pel\\PelExif",
            "type":"->"
         },
         {
            "file":"/apps/maps/vendor/lsolesen/pel/src/PelJpeg.php",
            "line":126,
            "function":"load",
            "class":"lsolesen\\pel\\PelJpeg",
            "type":"->"
         },
         {
            "file":"/apps/maps/lib/Service/PhotofilesService.php",
            "line":442,
            "function":"__construct",
            "class":"lsolesen\\pel\\PelJpeg",
            "type":"->"
         },
         {
            "file":"/apps/maps/lib/Service/PhotofilesService.php",
            "line":384,
            "function":"getExifPelBackup",
            "class":"OCA\\Maps\\Service\\PhotofilesService",
            "type":"->"
         },
         {
            "file":"/apps/maps/lib/Service/PhotofilesService.php",
            "line":264,
            "function":"getExif",
            "class":"OCA\\Maps\\Service\\PhotofilesService",
            "type":"->"
         },
         {
            "file":"/apps/maps/lib/BackgroundJob/AddPhotoJob.php",
            "line":56,
            "function":"addPhotoNow",
            "class":"OCA\\Maps\\Service\\PhotofilesService",
            "type":"->"
         },
         {
            "file":"/lib/public/BackgroundJob/Job.php",
            "line":79,
            "function":"run",
            "class":"OCA\\Maps\\BackgroundJob\\AddPhotoJob",
            "type":"->"
         },
         {
            "file":"/lib/public/BackgroundJob/QueuedJob.php",
            "line":47,
            "function":"execute",
            "class":"OCP\\BackgroundJob\\Job",
            "type":"->"
         },
         {
            "file":"/cron.php",
            "line":128,
            "function":"execute",
            "class":"OCP\\BackgroundJob\\QueuedJob",
            "type":"->"
         }
      ],
      "File":"/apps/maps/vendor/lsolesen/pel/src/PelIfd.php",
      "Line":447,
      "CustomMessage":"--"
   },
   "id":"61d4adc080563"
}
```

**Comment by spalinger** [comment]
Uninstalling the App Maps and installing it again helped, I don't see a blocked cron job or the error anymore for the last 24 hours since doing that.
NC 23.0.0, not on Docker.

**Comment by GHJester** [comment]
@spalinger yes, I don't see the error message anymore. I don't know why. But what I'm facing now is that a lot of pictures are not displayed anymore. I only see around 1k pictures out of more than 10K on the map

**Comment by umgfoin** [comment]
This is a problem in upstream dependency [PEL](https://github.com/pel/pel):
Currently [version 0.9.7 ](https://github.com/nextcloud/maps/blob/d4f3df133a30a2e2463309cd413aac2cd95141ee/composer.lock#L11)is pulled in. PEL-version 0.9.10 fixes some but not all of the problems.
@Mondrake's [PR ](https://github.com/mondrake/pel/tree/gh-actions)seems to work well with NC23 & PHP8.0, but it hasn't been merged, yet.

**Comment by umgfoin** [comment]
duplicate of #640

**Comment by weberhofer** [comment]
Please check, if the latest unstable version (as of Feb 4th 2022) fixes your issue.

**Comment by RDobrinov** [comment]
Fixed! Checked with nextcloud docker image and maps 0.1.10.

**Comment by GHJester** [comment]
No, I cannot confirm that. Still have the same issue:

~$ sudo docker exec -u www-data nextcloud php cron.php
TypeError: Unsupported operand types: int * string in /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php:447
Stack trace:
#0 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php(368): lsolesen\pel\PelIfd->loadSingleValue(Object(lsolesen\pel\PelDataWindow), 175, 24, 0)
#1 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php(350): lsolesen\pel\PelIfd->load(Object(lsolesen\pel\PelDataWindow), 175)
#2 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelTiff.php(159): lsolesen\pel\PelIfd->load(Object(lsolesen\pel\PelDataWindow), 10)
#3 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelExif.php(108): lsolesen\pel\PelTiff->load(Object(lsolesen\pel\PelDataWindow))
#4 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(216): lsolesen\pel\PelExif->load(Object(lsolesen\pel\PelDataWindow))
#5 /var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(126): lsolesen\pel\PelJpeg->load(Object(lsolesen\pel\PelDataWindow))
#6 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(442): lsolesen\pel\PelJpeg->__construct(Object(lsolesen\pel\PelDataWindow))
#7 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(384): OCA\Maps\Service\PhotofilesService->getExifPelBackup(Object(OC\Files\Node\File))
#8 /var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php(264): OCA\Maps\Service\PhotofilesService->getExif(Object(OC\Files\Node\File))
#9 /var/www/html/custom_apps/maps/lib/BackgroundJob/AddPhotoJob.php(56): OCA\Maps\Service\PhotofilesService->addPhotoNow(Object(OC\Files\Node\File), 'irene')
#10 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\Maps\BackgroundJob\AddPhotoJob->run(Array)
#11 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#12 /var/www/html/cron.php(150): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#13 {main}
`

Nextcloud version 23.0.3
maps version 0.1.10

**Comment by tobkra** [comment]
Just to chime in: I have the same problem running Nextcloud 22.0.6 and PHP8.0

**Comment by tobkra** [comment]
> Just to chime in: I have the same problem running Nextcloud 22.0.6 and PHP8.0

And after upgrading to 23.0.3 I still receive the same error
```
wwwhost /var/www/htdocs/owncloud # sudo -u apache php -f /var/www/htdocs/nextcloud-23.0.3/cron.php
TypeError: Unsupported operand types: int * string in /var/www/htdocs/nextcloud-23.0.3/apps/maps/vendor/lsolesen/pel/src/PelIfd.php:447
Stack trace:
#0 /var/www/htdocs/nextcloud-23.0.3/apps/maps/vendor/lsolesen/pel/src/PelCanonMakerNotes.php(215): lsolesen\pel\PelIfd->loadSingleValue()
#1 /var/www/htdocs/nextcloud-23.0.3/apps/maps/vendor/lsolesen/pel/src/PelIfd.php(406): lsolesen\pel\PelCanonMakerNotes->load()
#2 /var/www/htdocs/nextcloud-23.0.3/apps/maps/vendor/lsolesen/pel/src/PelTiff.php(159): lsolesen\pel\PelIfd->load()
#3 /var/www/htdocs/nextcloud-23.0.3/apps/maps/vendor/lsolesen/pel/src/PelExif.php(108): lsolesen\pel\PelTiff->load()
#4 /var/www/htdocs/nextcloud-23.0.3/apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(216): lsolesen\pel\PelExif->load()
#5 /var/www/htdocs/nextcloud-23.0.3/apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(126): lsolesen\pel\PelJpeg->load()
#6 /var/www/htdocs/nextcloud-23.0.3/apps/maps/lib/Service/PhotofilesService.php(442): lsolesen\pel\PelJpeg->__construct()
#7 /var/www/htdocs/nextcloud-23.0.3/apps/maps/lib/Service/PhotofilesService.php(384): OCA\Maps\Service\PhotofilesService->getExifPelBackup()
#8 /var/www/htdocs/nextcloud-23.0.3/apps/maps/lib/Service/PhotofilesService.php(264): OCA\Maps\Service\PhotofilesService->getExif()
#9 /var/www/htdocs/nextcloud-23.0.3/apps/maps/lib/BackgroundJob/AddPhotoJob.php(56): OCA\Maps\Service\PhotofilesService->addPhotoNow()
#10 /var/www/htdocs/nextcloud-23.0.3/lib/public/BackgroundJob/Job.php(79): OCA\Maps\BackgroundJob\AddPhotoJob->run()
#11 /var/www/htdocs/nextcloud-23.0.3/lib/public/BackgroundJob/QueuedJob.php(47): OCP\BackgroundJob\Job->execute()
#12 /var/www/htdocs/nextcloud-23.0.3/cron.php(150): OCP\BackgroundJob\QueuedJob->execute()
#13 {main}
```

**Comment by RDobrinov** [comment]
You've made a mistake. Maps using [PEL: PHP Exif Library](https://github.com/pel/pel). To solve problem with TypeError, download src directory from latest unstable version of PEL and replace files in html/custom_apps/maps/vendor/lsolesen/pel/src/

**Comment by umgfoin** [comment]
@tobkra, @GHJester,
Maps is not PHP8 ready, yet.
In order to get these problems fixed:
- downgrade to PHP7.x and wait for the next release, which, expectedly, will include the changes discussed here.
- pull, build and install current master, which implements PHP8 support (without claim to completeness).

**Comment by melle2** [comment]
@umgfoin this is not possible for me as PHP comes with the nextcloud docker image. Unfortunately I have to wait until it is fixed completely.

**Comment by tacruc** [comment]
duplicate #640
